name: Deploy to Dev

on: [deployment]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v1'
      - name: 'Deployment pending'
        uses: 'deliverybot/status@master'
        with:
          state: 'pending'
          token: '${{secrets.GITHUB_TOKEN}}'
      - name: 'Setup python'
        uses: actions/setup-python@v1
        with:
          python-version: '2.7.x'
          architecture: 'x64'
      
      # Actual deployment
      - name: 'Deploy ${{ github.event.deployment.environment }}'
        run: |
          echo "task - ${{ github.event.deployment.task }}"
          echo "environment - ${{ github.event.deployment.environment }}"
          echo "payload - ${{ toJson(github.event.deployment.payload) }}"
          ls
        
      - name: 'Install packages'
        run: |
          pip install mysql-python
          pip install -t lib codeforlife-portal
          pip install -t lib --pre --upgrade --no-deps aimmo
          rm -rf lib/pytz lib/pytz*.dist-info
      
      - name: 'Collect resources'
        run: python manage.py collectstatic --noinput
      
      
      - name: 'Restart MySQL'
        run: |
          sudo sed -i '/\[mysqld\]/assl = 1' /etc/mysql/mysql.conf.d/mysqld.cnf
          sudo service mysql restart

      - name: 'deployment success'
        if: success()
        uses: 'deliverybot/status@master'
        with:
          state: 'success'
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'deployment failure'
        if: failure()
        uses: 'deliverybot/status@master'
        with:
          state: 'failure'
          token: '${{ secrets.GITHUB_TOKEN }}' 
